### ISSUE TITLE
smhasher analysis

### ISSUE THREAD

**Issue by rurban** [Keith-Cancel/k-hashv#1]
it is now integrated into smhasher, all tests pass.
https://github.com/rurban/smhasher/

it's pretty fast, but there's a big problem: in most cases khashv_hash_vector is not inlined.
and the codesize is pretty big.

**Comment by Keith-Cancel** [comment]
I will try and look at it this evening when I get a little more time to figure out if I can figure out why it's not in-lining. If you have any examples or a place to zero in on that would be great.

I will add I notice your calling prep seed in every call to the test function which not reflect normal usage. You could either set the struct members directly or use `khashv_prep_seed128()` which does nothing else but set the seed struct. The `khashv_prep_seed32()` and  `khashv_prep_seed64()` do a little extra work to avoid for instance `0xffffffff` and `0x00000000ffffffff` being treated the same seed. Mainly using the final mixing function permute the bits.

**Comment by rurban** [comment]
Yes, prep_seed is unnecessary. Will fix that.

**Comment by Keith-Cancel** [comment]
Do you have the binaries for both the builds before the change? I find it interesting that it got slower when looking at the diffs. I am wondering what happened? When looking at these, moving the seeding outside the hot loops should have just decreased the latency. 

https://github.com/rurban/smhasher/commit/306a533d023431287d69bc83fe8e7ba9d1638e5b#diff-a19735dd699653b53026705c7618a79584242184dee0f6ea7e21bb5c5b6bf4a0

https://github.com/rurban/smhasher/commit/306a533d023431287d69bc83fe8e7ba9d1638e5b#diff-a593d27a47a069621b3affb539f34c685bd7a2a04a9f787aef1bb0d5d874073a

Want to disassemble the two binaries and figure out what happened here, because looking at those that's a huge delta.

**Comment by Keith-Cancel** [comment]
Closing for now.
